<?php
// Check if the form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Retrieve form data
    $patientName = $_POST['patientName'];
    $age = $_POST['age'];
    $gender = $_POST['gender'];
    $address = $_POST['address'];
    $phoneNumber = $_POST['phoneNumber'];
    $email = $_POST['email'];
    $disease = $_POST['disease'];
    $diseaseSpan = $_POST['diseaseSpan'];
    $paymentId = $_POST['paymentId']; // Payment ID generated by Razorpay

    // Database connection parameters
    $servername = "localhost"; // Replace with your server name
    $username = "username"; // Replace with your database username
    $password = "password"; // Replace with your database password
    $dbname = "your_database"; // Replace with your database name

    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);

    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    // Prepare SQL statement to insert data into database
    $sql = "INSERT INTO patients (patientName, age, gender, address, phoneNumber, email, disease, diseaseSpan, paymentId)
            VALUES ('$patientName', '$age', '$gender', '$address', '$phoneNumber', '$email', '$disease', '$diseaseSpan', '$paymentId')";

    // Execute SQL statement
    if ($conn->query($sql) === TRUE) {
        echo "New record created successfully";
    } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
    }

    // Close database connection
    $conn->close();
}
?>
